services:
# docker-compose.ymlのファイル基本構成でサービスを定義するために必要
  app:
  # appというサービス名
    build: ./
    # Dockerイメージベルドを指定
    # ./は現在のディレクトリを指して、Dockerfileを使ってイメージビルドしてる
    volumes:
      - .:/review
      # 現在のディレクトリとファイルシステムがリンクされる
    ports:
      - 3000:3000
      # ポート3000を開放
    